---
- name: Set Enforce password history to 24 or more passwords | cis enforce-password-history 1.1.1
  win_command: net accounts /uniquepw:24

- name: Set Maximum  password age to 45 or more days | cis minimum-password-age 1.1.2
  win_command: net accounts /maxpwage:45

- name: Set Minimum password age to 1 or more days | cis minimum-password-age 1.1.3
  win_command: net accounts /minpwage:1

- name: Set Minimum password length to 14 or more characters | cis minimum-password-length 1.1.4
  win_command: net accounts /minpwlen:14

- name: Set Lockout Duration | cis account-lockout 1.1.5
  win_command: net accounts /lockoutduration:30

- name: Set Lockout Window | cis account-window 1.1.6
  win_command: net accounts /lockoutwindow:30

- name: Set Lockout Threshold | cis account-window 1.1.7
  win_command: net accounts /lockoutthreshold:5
