---

- name: check if dnscrypt archive is present
  win_stat: path="{{ harden_win_temp_dir }}\\{{ harden_win_simplednscrypt_url | basename }}"
  register: dnscryptdl
- name: Download dnscrypt
  win_get_url:
    url: "{{ harden_win_simplednscrypt_url }}"
    dest: "{{ harden_win_temp_dir }}\\{{ harden_win_simplednscrypt_url | basename }}"
## FIXME! no checksum option, https://github.com/ansible/ansible-modules-core/issues/4901
  when: not dnscryptdl.stat.exists

## FIXME! not idempotent
- name: Install dnscrypt
  win_msi:
    path: "{{ harden_win_temp_dir }}\\{{ harden_win_simplednscrypt_url | basename }}"
    state: present
    wait: true


