---
- name: kitchen_test_role
  hosts: windows-servers
  roles:
    - ansible-windows-hardening
  vars:
    win_security_policy_rights:
      SeRemoteInteractiveLogonRight: '*S-1-1-0, *S-1-5-32-544, *S-1-5-32-545, *S-1-5-32-551'
      SeTcbPrivilege: '*S-1-0-0'
      SeMachineAccountPrivilege: '*S-1-5-32-544'
      SeTrustedCredManAccessPrivilege: '*S-1-0-0'
      SeNetworkLogonRight: '*S-1-1-0, *S-1-5-32-544, *S-1-5-32-545, *S-1-5-32-551'
