---
- name: sysctl
  become: yes
  become_method: sudo
  template:
    src: etc/sysctl.conf.j2
    dest: /etc/sysctl.d/10-kernel-hardening.conf
    backup: yes
    mode: 0600
    owner: root
    group: root
  notify:
    - restart sysctl
  tags:
    - sysctl
    - security
...
