---
# CCE-27068-6
# CCE-80202-5
# CCE-80204-1
# CCE-27557-8

- name: stat init.d/rc
  become: yes
  become_method: sudo
  stat:
    path: /etc/init.d/rc
  register: initdrc

- name: set default rc umask
  become: yes
  become_method: sudo
  replace:
    regexp: 'umask(\s+.*)'
    replace: "umask 027"
    dest: /etc/init.d/rc
    mode: 0755
  when: initdrc.stat.exists
  tags:
    - umask
    - security

- name: set default init umask
  become: yes
  become_method: sudo
  replace:
    regexp: 'umask(\s+.*)'
    replace: "umask 027"
    dest: /etc/sysconfig/init
    mode: 0755
  when: ansible_distribution == "CentOS"
  tags:
    - umask
    - security

- name: stat bashrc
  become: yes
  become_method: sudo
  stat:
    path: /etc/bashrc
  register: bashrc

- name: set default bashrc umask
  become: yes
  become_method: sudo
  replace:
    regexp: 'umask(\s+.*)'
    replace: "umask 027"
    dest: /etc/bashrc
    mode: 0644
  when: bashrc.stat.exists
  tags:
    - umask
    - security

- name: stat csh.cshrc
  become: yes
  become_method: sudo
  stat:
    path: /etc/csh.cshrc
  register: cshrc

- name: set default csh.cshrc umask
  become: yes
  become_method: sudo
  replace:
    regexp: 'umask(\s+.*)'
    replace: "umask 027"
    dest: /etc/csh.cshrc
    mode: 0644
  when: cshrc.stat.exists
  tags:
    - umask
    - security

- name: set default profile umask
  become: yes
  become_method: sudo
  replace:
    regexp: 'umask(\s+.*)'
    replace: "umask 027"
    dest: /etc/profile
    mode: 0644
  tags:
    - umask
    - security


- name: export TMOUT
  become: yes
  become_method: sudo
  lineinfile:
    line: "export TMOUT=900"
    dest: /etc/profile
    mode: 0644
    state: present
    create: no
    insertbefore: "^export"
  tags:
    - tmout
    - security
...
