---
- name: rkhunter
  become: yes
  become_method: sudo
  template:
    src: etc/default/rkhunter.j2
    dest: /etc/default/rkhunter
    backup: yes
    mode: 0644
    owner: root
    group: root
  when: ansible_distribution == "Ubuntu"
  notify:
    - rkhunter propupd
  tags:
    - packages
    - rkhunter
    - security

- name: rkhunter ssh root user
  become: yes
  become_method: sudo
  lineinfile:
    regexp: "ALLOW_SSH_ROOT_USER"
    line: "ALLOW_SSH_ROOT_USER=no"
    dest: /etc/rkhunter.conf
    mode: 0640
    state: present
    create: no
    backrefs: yes
  notify:
    - rkhunter propupd
  tags:
    - packages
    - rkhunter
    - security

- name: rkhunter ssh proto
  become: yes
  become_method: sudo
  lineinfile:
    regexp: "ALLOW_SSH_PROT_V1"
    line: "ALLOW_SSH_PROT_V1=0"
    dest: /etc/rkhunter.conf
    mode: 0640
    state: present
    create: no
    backrefs: yes
  notify:
    - rkhunter propupd
  tags:
    - packages
    - rkhunter
    - security
...
