---
- name: reload auditd
  become: yes
  become_method: sudo
  service:
    name: auditd
    state: reloaded

- name: generate auditd
  become: yes
  become_method: sudo
  command: augenrules

- name: restart sysctl
  become: yes
  become_method: sudo
  service:
    name: systemd-sysctl
    state: restarted

- name: reload systemd
  become: yes
  become_method: sudo
  command: systemctl daemon-reload

- name: rkhunter propupd
  become: yes
  become_method: sudo
  command: rkhunter --propupd

- name: enable aidecheck
  become: yes
  become_method: sudo
  command: systemctl reenable aidecheck.timer

- name: start aidecheck
  become: yes
  become_method: sudo
  command: systemctl start aidecheck.timer

- name: disable aidecheck
  become: yes
  become_method: sudo
  command: systemctl disable aidecheck.timer

- name: mask aidecheck
  become: yes
  become_method: sudo
  command: systemctl mask aidecheck.timer

- name: restart sshd
  become: yes
  become_method: sudo
  service:
    name: sshd
    state: restarted

- name: apt-get autoremove
  become: yes
  become_method: sudo
  command: apt-get -y autoremove

- name: apt-get clean
  become: yes
  become_method: sudo
  command: apt-get -y clean

- name: mask apport
  become: yes
  become_method: sudo
  command: systemctl mask apport.service

- name: yum clean
  become: yes
  become_method: sudo
  command: yum -y clean all

- name: enable haveged
  become: yes
  become_method: sudo
  command: systemctl enable haveged

- name: update authconfig
  become: yes
  become_method: sudo
  command: authconfig --updateall
...
