---

harden_win_networkpath: ''
harden_win_networkdrive: ''
harden_win_temp_dir: 'c:\harden_log'

## Windows
harden_win_securityupdates: true
harden_win_services: true
harden_win_registry: true
harden_win_gpo_local: false
harden_win_gpo_inf: win7-computer-security.inf
harden_win_gpo_db: "%systemRoot%\\security\\database\\newdb.sdb"
harden_win_gpo_log: c:\windows\temp\secedit.txt
## User Account Control: Run all administrators in Admin Approval Mode
harden_win_gpo_EnableLUA: true
## Note: this one corrupts win10 eval currently...
harden_win_lsa_harden: false
## win7
#harden_win_emet_path: 'c:\Program Files (x86)\EMET 5.5'
## win10
harden_win_emet_path: 'c:\Program Files\EMET 5.5'
harden_win_emet_conf: "{{ harden_win_emet_path }}\\Deployment\\Protection Profiles\\Recommended Software.xml"
harden_win_vss: true
harden_win_wmi_monitor: true
harden_win_flash: true
harden_win_adobereader: true
#harden_win_adobereader_v: '11.0'
harden_win_adobereader_v: 'DC'
## 300MB = 314572 (default in kb) = 315801600
## Reco Microsoft 4GB, https://support.microsoft.com/en-ca/kb/957662
harden_win_eventlogs_maxsize: 315801600

harden_windows_disable_wpad: true

harden_windows_disable_cmd: false

harden_win_ie_proxy: false
harden_win_ie_proxy_url: ''
harden_win_ie_proxy_override: ''

## if empty, will go in User documents
## Note: env variable are not resolved
#harden_win_powershell_transcription_dir: ''
#harden_win_powershell_transcription_dir: "%USERPROFILE%\\AppData\\Roaming\\PowershellTranscripts"
harden_win_powershell_transcription_dir: "c:\\Windows\\Logs\\PowershellTranscripts"

harden_windows_disable_win10cortana: true

harden_win_restrict_dma: false

harden_win_chocolateypkgs:
# http://windows.microsoft.com/en-us/windows/security-essentials-all-versions
## FAIL since 4m: https://gist.github.com/choco-bot/85701f4e87e16efed5be
#    - microsoftsecurityessentials
## v5.5.2, oct 2016
    - emet
## v5.0, oct 2016
    - powershell
## for test
#    - adobereader
    - procexp
#    - sysinternals
#    - gmer
#    - gpg4win
#    - gpg4usb
## install fails for me... "Exception calling "SetAccessRule" ... Some or all identity references could not be translated."
#    - osquery

harden_win_sysmon: true
harden_win_sysmon_url: 'https://download.sysinternals.com/files/Sysmon.zip'
## note: file should be in current or template directory with .j2 extension
harden_win_sysmon_template: SysmonConfig-Neo23x0-server.xml

## win_get_url missing checksum check
harden_win_remotelogging: false
harden_win_remotelogging_nxlog_url: 'https://nxlog.co/system/files/products/files/1/nxlog-ce-2.9.1716.msi'

harden_win_netcease: true
harden_win_netcease_url: 'https://gallery.technet.microsoft.com/Net-Cease-Blocking-Net-1e8dcb5b/file/165596/1/NetCease.zip'

harden_win_simplednscrypt: true
harden_win_simplednscrypt_url: https://github.com/bitbeans/SimpleDnsCrypt/releases/download/0.4.0/SimpleDNSCrypt.msi

harden_win_osquery: true
harden_win_osqueryd_service_enable: true
harden_win_osquery_template: 'osquery.conf.j2'
## extra files to upload as packs
harden_win_osquery_upload_packs: []
harden_win_osquery_packs:
    - "osquery-monitoring"
    - "incident-response"
    - "it-compliance"
    - "vuln-management"
    - "hardware-monitoring"
## currently only chocolatey release
harden_win_osquery_url: ''

## Experimental
harden_win_mbrfilter: false
harden_win_mbrfilter_url: https://github.com/yyounan/MBRFilter/files/536998/64.zip
harden_win_restrict_usb: false

harden_win_services_disable:
    - AdobeLM Service
    - Bluetooth Support Service
    - Xbox Live Game Save
    - Xbox Live Auth Manager
    - Windows Mobile Hotspot Service
    - Enterprise App Management Service
    - Fast User Switching Compatibility
    - Error Reporting Service
    - FTP Publishing
    - InstallDriver Table Manager
    - Windows Messenger
    - NetMeeting Remote Desktop Sharing
    - NT LM Security Support Provider
    - Remote Desktop Help Session Manager
    - Smart Card
    - Telnet
    - Uninterrupted Power Supply
    - Volume Shadow Copy
    - Windows Firewall/Internet Connection Sharing (ICS)
    - Fax
    - Offline Files
    - Geolocation Service
    - Sensor Service
    - RetailDemo
    #- iphlpsvc
    #- WinHttpAutoProxySvc
    #- NcaSvc
    #- PolicyAgent
    - IKEEXT
    - MSiSCSI
    - diagnosticshub.standardcollector.service
    - DiagTrack
    - dmwappushservice
    - HomeGroupListener
    - HomeGroupProvider
    - lfsvc
    - MapsBroker
    - NetTcpPortSharing
    #- RemoteRegistry
    - SharedAccess
    - TrkWks
    - WbioSrvc
    - WMPNetworkSvc
    - XblAuthManager
    - XblGameSave
    - XboxNetApiSvc
    - Help and Support
    - Indexing Service 
    - Install Driver Table Manager
    - NetMeeting Remote Desktop Sharing 
    - NVIDIA Display Driver Service
    - Office Source Engine
    - Print Spooler 
    - Protected Storage
    - Removable Storage
    - Security Center
    - Telnet 
    - Uninterrupted Power Supply
    - Volume Shadow Copy
    - Windows Media Connect
    - Windows Media Connect Helper
    - Wireless Zero Configuration
    - WMI Performance Adapters

harden_win_services_manual:
    - Application Management
    - Cryptographic Services
    - Distributed Transaction Service
    - Help and Support
    - HTTP SSL
    - IMAPI CD-Burning COM Service
    - IPSEC Services
    - MS Software Shadow Copy Provider
    - Portable Media Serial Number Service
    - Remote Procedure Call Locator
    - Removable Storage
    - Secondary Logon
    - Server
    - TCP/IP NetBIOS Helper
    - Universal Plug and Play Device Host
    - User Privilege Service
    - Human Interface Device Access
    - IMAPI CD-Burning COM Service
    - IPSEC Services
    - MS Software Shadow Copy Provider
    - Portable Media Serial Number Service
    - Remote Procedure Call Locator
    - Routing and Remote Access
    - TCP/IP NetBIOS Helper
    - Universal Plug and Play Device Host
    - User Privilege Service
    - Windows Image Acquisition 
    - Workstation
    - Remote Registry

## Experimental. issue with ansible win_firewall_rule module
harden_win_firewall: false
#harden_win_fw_default_action: 'allow'
harden_win_fw_default_action: 'block'
harden_win_fw_program_allowed_out_public:
  - '%ProgramFiles\firefox.exe'
  - '%ProgramFiles%\Google\Chrome\Application\chrome.exe'
  - '%windir%\SystemApps\Microsoft.MicrosoftEdge_8wekyb3d8bbwe\MicrosoftEdge.exe'
  - 'microsoftupdate.exe'
  - '%windir%\System32\BackgroundTransferHost.exe'
  - '%ProgramFiles%\bitbeans\Simple DNSCrypt\dnscrypt-proxy\dnscrypt-proxy.exe'
  - '%ProgramFiles%\bitbeans\Simple DNSCrypt\dnscrypt-proxy\dnscrypt-proxy-secondary.exe'
harden_win_fw_program_blocked_out_public:
  - "C:\\Program Files\\Microsoft Office\\Office14\\winword.exe"
  - "C:\\Program Files\\Microsoft Office\\Office14\\excel.exe"
  - "C:\\Program Files\\Microsoft Office\\Office14\\powerpoint.exe"
  - "C:\\Program Files\\Microsoft Office\\Office14\\msaccess.exe"
  - '%SystemRoot%\System32\wscript.exe'
  - '%SystemRoot%\Syswow64\wscript.exe'
  - '%SystemRoot%\System32\cscript.exe'
  - '%SystemRoot%\Syswow64\cscript.exe'
  - '%SystemRoot%\system32\mshta.exe'
  - '%SystemRoot%\SysWOW64\WindowsPowerShell\v1.0\powershell.exe'
  - '%SystemRoot%\system32\WindowsPowerShell\v1.0\powershell.exe'
  - '%SystemRoot%\system32\cmd.exe'
## https://labs.nettitude.com/blog/fun-with-windows-binaries-application-whitelist-bypass-using-msiexec/
  - msiexec.exe
harden_win_fw_ports_allowed_out_public: []
harden_win_fw_ports_blocked_out_public:
  - 25
  - 587
  - 53
  - 123
  - 6881-6889
harden_win_fw_ports_allowed_in_public: []
harden_win_fw_ports_blocked_in_public:
  - 25
  - 587
  - 80
  - 443
  - 8080
  - 53
  - 123
  - 6881-6889

## FIXME! localized rule name...
harden_win_fw_rules_disable:
  - Xbox
  - Xbox Game UI
  - Xbox Identity Provider
  - Cortana
  - Candy Crush Soda Saga
harden_win_fw_prefix: "A-Ansible"

harden_win_suspicious_ext:
    - hta
    - vbe
    - vbs
    - VBE
## https://isc.sans.edu/diary/Controlling+JavaScript+Malware+Before+it+Runs/21171
    - js
    - jse
    - sct
    - wsc
    - wsf
    - wsh
    - pif
    - bat

## https://support.microsoft.com/en-us/help/2696547/how-to-enable-and-disable-smbv1,-smbv2,-and-smbv3-in-windows-vista,-windows-server-2008,-windows-7,-windows-server-2008-r2,-windows-8,-and-windows-server-2012
harden_win_disable_smb_proto:
    - SMB1
#    - SMB2

